### ISSUE TITLE
JSD-REDESIGN: What shall we include in the "Services" page?

### ISSUE THREAD

**Issue by zsediqyar** [jsdesigns-web-development/jsd-redesign#5]

**Comment by holaymolay** [comment]
- Small Business Website Design
- e-Commerce Website Design
- Hosting
- Email Mangement & Hosting
- Software Development
- Small Business Brand Development

**Comment by holaymolay** [comment]
I'm not going to focus on SEO right now.

**Comment by zsediqyar** [comment]
What does this mean? "_I'm not going to focus on SEO right now._"

**Comment by holaymolay** [comment]
It means that we have to be more focused. About what we do and what we offer. SEO is very time-consuming and I just cannot make it a service because I don't have the time for it. I'll continue to do SEO for our website and avs private security, but beyond that, I will not. If we want to hire someone in the future, we can. Or you are welcome to be our SEO guru, if it's something you'd like to do.
